name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install Go dependencies
        run: go mod download

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install SecTesterJS dependencies
        run: npm install --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

      - name: Start application
        run: |
          nohup go run main.go &
          until nc -zv 127.0.0.1 9000; do sleep 1; done

      - name: Configure Bright credentials
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: gFFBCRBWhgL3uPxAc4Qkq1
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: gFFBCRBWhgL3uPxAc4Qkq1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:9000
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4
